--O COMANDO A SEGUIR É O COMANDO USADA PARA VISUALIZAR UMA TABELA DE UM BANCO DE DADOS DIFERENTE DAQUELE NO QUAL VOCÊ ESTÁ FAZENDO A CONSULTA
SELECT * FROM SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS;;
--NOTE QUE PRIMEIRO É INFORMADO O NOME DO BANCO, SEGUIDO DO COMANDO 'DBO', E EM SEGUIDA É INFORMADA A TABELA QUE SE DESEJA

/*ESTE COMANDO É USADO, POR EXEMPLO, PARA FAZER A IMPORTAÇÃO DE DADOS DE UM BANCO PARA OUTRO. PARA ISSO, É IMPORTANTE FAZER UMA CONSULTA NO BANCO DE 
ORIGEM, PASSANDO OS CAMPOS CORRESPONDENTES NA MESMA ORDEM EM QUE APARECEM NO CAMPO DE DESTINO, E TAMBÉM É PRECISO QUE OS CAMPOS ESTEJAM COM O MESMO NOME
QUE NA TABELA DE DESTINO, POR ISSO É IMPORTANTE FAZER USO DO ALIAS 'AS'. FICARIA DA SEGUINTE FORMA, ENTÃO, PARA FAZER A IMPORTAÇÃO DA TABELA 
'TABELA_DE_PRODUTOS' DO BANCO 'SUCOS_FRUTAS' PARA A TABELA 'PRODUTOS' DO BANCO VENDAS_SUCOS*/

SELECT
--CAMPOS NA ORDEM EM QUE APARECEM SEUS CORRESPONDENTES NA TABELA 'PRODUTOS' DO BANCOS VENDAS_SUCOS
	CODIGO_DO_PRODUTO		AS CODIGO, 
	NOME_DO_PRODUTO			AS DESCRITOR,
	SABOR					AS SABOR,
	TAMANHO					AS TAMANHO,
	EMBALAGEM				AS EMBALAGEM,
	PRECO_DE_LISTA			AS PRECO_LISTA

FROM SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS

--TENDO ESSE COMANDO EM MÃOS, PODEMOS USÁ-LO PARA PASSAR OS DADOS PARA O OUTRO BANCO DA SEGUINTE FORMA:

INSERT INTO PRODUTOS
	SELECT

		CODIGO_DO_PRODUTO		AS CODIGO, 
		NOME_DO_PRODUTO			AS DESCRITOR,
		SABOR					AS SABOR,
		TAMANHO					AS TAMANHO,
		EMBALAGEM				AS EMBALAGEM,
		PRECO_DE_LISTA			AS PRECO_LISTA

	FROM SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS

/*CASO HAJA INFORMAÇÕES REPETIDAS, É IMPORTANTE FILTRÁ-LAS, VISTO QUE NÃO SERÁ POSSÍVEL EXECUTAR O COMANDO POR CONFLITO DE CHAVES PRIMÁRIAS, QUE DEVEM SER
ÚNICAS*/


--INSERINDO DADOS NA TABELA 'CLIENTES'
INSERT INTO CLIENTES
	SELECT
		
		CPF,
		NOME,
		ENDERECO_1				AS		ENDERECO,
		BAIRRO,
		CIDADE,
		ESTADO,
		CEP,
		DATA_DE_NASCIMENTO		AS		DATA_NASCIMENTO,
		IDADE,
		GENERO,
		LIMITE_DE_CREDITO		AS		LIMITE_CREDITO,
		VOLUME_DE_COMPRA		AS		VOLUME_COMPRA,
		PRIMEIRA_COMPRA

	FROM SUCOS_FRUTAS.DBO.TABELA_DE_CLIENTES
	WHERE
		
		CPF NOT IN ('1471156710', '19290992743', '2600586709')