SELECT
	GETDATE()		AS		HOJE,
	DATEADD(DAY, 10, GETDATE())		AS		DAQUI_DEZ_DIAS,
	DATEDIFF(DAY, '2024-01-01', GETDATE())	AS	DIAS_ATE_ANO_NOVO
--GETDATA() RECEBE A DATA E HORA DO COMPUTADOR
--DATEADD() SOMA OU SUBTRAI A QUANTIDADE PASSADA (10) DE PERÍODO(DAY) DE UMA DATA
--DATEDIFF() RETORNA O VALOR, EM DETERMINADO PERÍDODO (DAY), DA DIFERENÇA ENTRE DUAS DATAS 

SELECT DATEPART(MONTH, GETDATE()) AS DIA_DE_HOJE
--DATEPART() RETORNA O PERÍODO ESPECIFICADO (MONTH) DA DATA PASSADA

SELECT ISDATE(DATETIMEFROMPARTS(2022,02,28,00,00,00,00))
--ISDATE() RETORNA UM VALOR BOLEANO SE UMA DATA EXISTE OU NÃO
--DATETIMEFROMPARTS() RETORNA UMA DATA BASEADA NOS VALORES PASSADOS AAAA/MM/DD/HH/MM/SS/MS

SELECT 

	NOME + ' nasceu em ' + 
	DATENAME (WEEKDAY,DATA_DE_NASCIMENTO) + ',' +
	DATENAME (DAY,DATA_DE_NASCIMENTO) + ' de ' +
	DATENAME(MONTH, DATA_DE_NASCIMENTO) + ' de ' +
	DATENAME(YEAR, DATA_DE_NASCIMENTO) AS DATA_EXTENSO

FROM TABELA_DE_CLIENTES;
--DATENAME() RETORNA A DATA POR EXTENSO
