/*CONVERT() FAZ A CONVERSÃO DE DATA EM TEXTO, USANDO COMO BASE UMA TABELA EM QUE CADA NÚMERO DELA
REPRESENTA UMA DAS FORMAS DE CONVERSÕES.*/
SELECT CONVERT(VARCHAR(10), GETDATE(), 121);
--CONVERTE A DATA E HORA ATUAL EM UM TEXTO DE 10 CARACTERES

SELECT CONVERT(VARCHAR(25), GETDATE(), 121);
/*AQUI, A ÚNICA DIFERENÇA FOI QUE AUMENTAMOS O NÚMERO DE CARACTERES DO VARCHAR, POSSIBILITANDO ENTÃO QUE O MODO
121 DE CONVERSÃO, QUE INCLUI ATÉ OS MILISSEGUNDOS, MOSTRASSE TODAS AS INFORMAÇÕES. É IMPORTANTE SE ATENTAR TAMBÉM
QUANTO À INFORMAÇÃO DE ORIGEM QUE É PASSADA POIS, CASO ELA NÃO POSSUA AS INFORMAÇÕES, ELAS TAMBÉM NÃO SERÃO
EXIBIDAS*/
SELECT CONVERT(VARCHAR(25), DATA_DE_NASCIMENTO, 121) FROM TABELA_DE_CLIENTES;

/*NESTE EXEMPLO, MESMO QUE O MODO DE CONVERSÃO INDICADO POSSUA DATA E HORA, O CAMPO DE ORIGEM (DATA_DE_NASCIMENTO)
NÃO POSSUI, ASSIM O RESULTADO MOSTRARÁ SOMENTE OS VALORES DE AAAA-MM-DD*/

/*CAST() FAZ CONVERSÃO DE NÚMEROS PARA NÚMEROS, ENTÃO É POSSÍVEL PEGAR UM NÚMERO INTEIRO E CONVERTÊ-LO EM
MONEY, FLOAT E ASSIM POR DIANTE. TAMBÉM POSSUI UMA TABELA QUE INFORMA AS POSSÍVEIS CONVERSÕES. EXISTEM CONVERSÕES
EXPLÍCITAS E IMPLÍCITAS. VEJA O EXEMPLO ABAIXO:*/

SELECT NOME_DO_PRODUTO, CONCAT('O PREÇO DE LISTA É: ', PRECO_DE_LISTA) FROM TABELA_DE_PRODUTOS
/*AQUI, A CONVERSÃO FOI FEITA SEM SER NECESSÁRIO FAZER NENHUMA DECLARAÇÃO, LOGO É UMA CONVERSÃO EXPLÍCITA.
CASO DÊ ALGUM PROBLEMA EM UMA CONVERÃO EXPLÍCITA, PODE SE FAZER DA SEGUINTE FORMA, USANDO O MESMO EXEMPLO:*/

SELECT 
	
	NOME_DO_PRODUTO, 
	CONCAT('O PREÇO DE LISTA É: ', CAST(PRECO_DE_LISTA AS VARCHAR(10)))

FROM TABELA_DE_PRODUTOS
--ESTA JÁ É UMA CONVERSÃO IMPLÍCITA, POIS FOI DECLARADA A CONVERSÃO.

SELECT

	CONCAT('O cliente ', TC.NOME,' comprou R$', STR(SUM(INF.PRECO * INF.QUANTIDADE), 10, 2),
	' no ano de 2016')	AS	COMPRA_CLIENTE

FROM NOTAS_FISCAIS NF
INNER JOIN TABELA_DE_CLIENTES TC
ON NF.CPF = TC.CPF
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO

WHERE 
	
	YEAR(NF.DATA_VENDA) = '2016'

GROUP BY

	TC.NOME, YEAR(NF.DATA_VENDA);
/*STR() CONVERTE UM NÚMERO EM STRING. RECEBE O VALOR (OBRIGATÓRIO), O TAMANHO (10 POR PADRÃO, OPICIONAL) E O
NÚMERO DE CASAS DECIMAIS EXIBIDOS (0 POR PADRÃO, OPICIONAL.*/