SELECT LOWER(NOME), UPPER(NOME) FROM TABELA_DE_CLIENTES;
--LOWER() RETORNA UMA STRING EM MINÚSCULA
--UPPER() RETORNA UMA STRING EM MAIÚSCULA

SELECT CONCAT(ENDERECO_1, ' ', BAIRRO, ' ', CIDADE, ' ', ESTADO, ' - ', CEP) FROM TABELA_DE_CLIENTES
--CONCAT() JUNTA STRINGS

SELECT

	NOME,
	LEFT(NOME, 4),
	RIGHT(NOME, 4)

FROM TABELA_DE_CLIENTES;
--LEFT() PEGA, DA ESQUERDA PARA DIREITA, O NÚMERO DE CHAR PASSADOS NO PARÂMETRO
--RIGHT() PEGA, DA DIREITA PARA ESQUERDA, O NÚMERO DE CHAR PASSADOS NO PARÂMETRO

SELECT REPLICATE(NOME, 3) FROM TABELA_DE_CLIENTES;
--REPLICATE() REPETA STRING PASSADA A QUANTIDADE DE VEZES CITADA NO PARÂMETRO


SELECT 

	NOME,
	SUBSTRING(NOME, 1, CHARINDEX(' ', NOME)) AS PRIMEIRO_NOME
	
FROM TABELA_DE_CLIENTES;
--SUBSTRING() RETORNA UMA PARTE DA STRING PASSADA NO PARÂMETRO, A PARTIR E ATÉ O PONTO MENCIONADO
--CHARINDEX() RETORNA O ÍNDICE DO VALOR PASSADO NA STRING

SELECT REPLACE((REPLACE(TAMANHO, 'Litros', 'L')), 'Litro', 'L') FROM TABELA_DE_PRODUTOS
--REPLACE() SUBSTITUI EM UMA STRING O VALOR PASSADO POR OUTRO