SELECT ROUND(3.437, 2), ROUND(3.433,2)
--ROUND() ARRODANDO PARA O NÚMERO REDONDO MAIS PRÓXIMO

SELECT FLOOR(3.433), CEILING(3.433)
--FLOOR() RETORNA O MENOR INTERIRO MENOR OU IGUAL AO VALOR PASSADO
--CEILING() RETORNA O MENOR INTERIRO MAIOR OU IGUAL AO VALOR PASSADO

SELECT POWER(2, 8), EXP(3)
--POWER() FAZ A POTÊNCIA DO PRIMEIRO NÚMERO COM O POTENCIAL DO SEGUNDO
--EXP() PEGA O VALOR DO NÚMERO EXPONENCIAL E ELEVA PELO VALOR PASSADO

SELECT SQRT(1000)
--SQRT() FAZ A RAIZ QUADRADA DO NÚMERO PASSADO

SELECT ABS(100), ABS(-56.7)
--ABS() ENCONTRA O NÚMERO ABSOLUTO DO VALOR PASSADO

SELECT TOP 5 * FROM NOTAS_FISCAIS
SELECT TOP 5 * FROM ITENS_NOTAS_FISCAIS

--MOSTRA O TOTAL E O TOTAL DE IMPOSTO PAGO POR NOTA FISCAL
SELECT

	FLOOR(INF.QUANTIDADE * INF.PRECO)						AS		TOTAL_PAGO,
	FLOOR((INF.QUANTIDADE * INF.PRECO) * NF.IMPOSTO)		AS		TOTAL_IMPOSTO,
	NF.DATA_VENDA											AS		DATA_VENDA


FROM ITENS_NOTAS_FISCAIS									INF

INNER JOIN NOTAS_FISCAIS									NF
ON INF.NUMERO = NF.NUMERO

WHERE

	NF.DATA_VENDA BETWEEN '20160101' AND '20161231';

--FAZ A SOMATÓRIA DO TOTAL DE IMPOSTO PAGO
SELECT

	YEAR(NF.DATA_VENDA)		AS		ANO,
	FLOOR(SUM((INF.QUANTIDADE * INF.PRECO) * NF.IMPOSTO))

FROM ITENS_NOTAS_FISCAIS INF
INNER JOIN NOTAS_FISCAIS NF
ON INF.NUMERO = NF.NUMERO

WHERE YEAR(DATA_VENDA) = '2016'

GROUP BY YEAR(DATA_VENDA);