/*UM CURSOR É UM OBJETO T-SQL QUE PERMITE PROCESSAR LINHA A LINHA DE UM CONJUNTO DE RESULTADO. BASICAMENTE, É DEFINIDA UMA CONSULTA COM VÁRIAS LINHAS, E EM SEGUIDA, ELAS SERÃO PERCORRIDAS COM UMA OU MAIS
OPERAÇÕES SENDO REALIZADAS NELA. VEJA UM EXEMPLO:*/

DECLARE @NOME VARCHAR(200), @CIDADE VARCHAR(200)
DECLARE CURSOR_1 CURSOR FOR		/*COMANDO PARA FAZER A CRIÇÃO DO CURSOR E DEFININDO A CONSULTA EM QUE ELE IRÁ PERCORRER. TAMBÉM NOTE QUE FOI CRIADA UMA VARIÁVEL QUE SERÁ USADO DURANTE A EXECUÇÃO DO CURSOR*/
	SELECT	NOME,
			CIDADE
	FROM [TABELA DE CLIENTES]

OPEN CURSOR_1	/*O COMANDO PARA ABRIR O CURSOR SERVE PARA QUE O SISTEMA ALOQUE RECURSOS PARA QUE O MESMO SEJA EXECUTADO, COMO ATRIBUIÇÃO DE MEMÓRIA E VERIFICAÇÃO DA CONSULTA*/
FETCH NEXT FROM CURSOR_1 INTO @NOME, @CIDADE		/*ESTE É O COMANDO PARA QUE O CURSOR PERCORRA LINHA POR LINHA E LEIA OS DADOS. NO CASO, AQUI DEFINIMOS PARA ELE PERCORRER A PRIMEIRA LINHA DA CONSULTA*/
WHILE @@FETCH_STATUS = 0	/*O WHILE É USADO PARA QUE O CURSOR PERCORRA AS LINHAS E EXECUTE AS AÇÕES NECESSÁRIAS. NOME QUE É NECESSÁRIA DEFINIR QUE ELE AVANÇA PARA A PRÓXIMA LINHA NO FIM PARA NÃO TER LOOP*/
BEGIN						/*@@FECTH_STATUS É UMA VARIÁVEL INTERNA DO SISTEMA QUE CONTA SE O CURSOR PERCORRE TOTALMENTE OU NÃO A CONSULTA. CASO SEU VALOR SEJA ZERO, AINDA HÁ LINHAS PARA SEREM PERCORRIDAS*/
	PRINT 'NOME:' + @NOME
	PRINT 'CIDADE:' + @CIDADE
	PRINT ''

	FETCH NEXT FROM CURSOR_1 INTO @NOME, @CIDADE /*AS VARIÁVEIS PRECISAM SER PASSADAS NA ORDEM DE CORRESPONDÊNCIA DA DEFINIÇÃO NA CONSULTA*/

END

CLOSE CURSOR_1 /*COM O CLOSE, O CURSOR SERÁ FECHADO PARA LIBERAR OS RECURSOS DO SISTEMA QUE ANTES ESTAVAM EMPENHADOS NO MESMO. APÓS FECHAR, NENHUMA OUTRA OPERAÇÃO PODERÁ SER REALIZADA SOBRE O CURSOR*/
DEALLOCATE CURSOR_1 /*APÓS FECHAR, A DEFINIÇÃO DO CURSOR E SEU ESTADO AINDA ESTÃO NA MEMÓRIA, ENTÃO É RECOMENDADO USAR O COMANDO DEALLOCATE PARA LIMPAR TOTALMENTE DA MEMÓRIA*/