/*DECLARAÇÃO DE VARIÁVEIS COM TSQL*/
--FORMA COMUM
DECLARE @NOME VARCHAR(100)
DECLARE @CPF VARCHAR (50)
DECLARE @IDADE INT

--TAMBÉM PODE SER FEITA DA SEGUINTE FORMA
--DECLARE @NOME VARCHAR(100), @CPF VARCHAR(50), @IDADE INT

/*A ATRIBUIÇÃO DOS VALORES DA VARIÁVEIS PODE SER TANTO ATRAVÉS DO COMANDO 'SET' QUANDO USANDO UM COMANDO SELECT, POR EXEMPLO:

SET:
SET @NOME = 'Érica Carvalho'
SET @CPF = '1471156710'
SET @IDADE = '27'

USANDO O SELECT, FICARIA ASSIM:
*/

SET @CPF = '1471156710'

SELECT @NOME = NOME, @IDADE = IDADE FROM [TABELA DE CLIENTES] WHERE CPF = @CPF;

PRINT @NOME;
PRINT @IDADE;

/*NO CASO, AINDA FOI USADO SET NA CONSULTA PARA USARMOS O CPF COMO CHAVE PRIMÁRIA E CONSTAR APENAS UM VALOR, MAS USANDO OUTROS FILTROS, NÃO SERIA NECESSÁRIO E O CPF PODERIA
SER INCLUSO DENTRO DO SELECT*/