/*	DESAFIO: VERIFICAR SE OS NÚMEROS NO INTERVALO DE 1 ATÉ 1000000 SÃO NOTAS FISCAIS.
	PARA FAZER A SOLUÇÃO DESTE DESAFIO, PODEMOS USAR O T-SQL E SUAS FUNÇÕES DA SEGUINTE FORMA
*/


DECLARE @LIMITE_MINIMO INT
DECLARE @LIMITE_MAXIMO INT
DECLARE @TABELA_NUMEROS TABLE (NUMERO INT, STATUS VARCHAR(200), FATURAMENTO FLOAT)
/*AO DECLARER UMA TABELA UMA TABELA COM @, ELA SÓ EXISTIRÁ DURANTE A CONSULTA EM QUE ELE ESTIVER SENDO EXECUTADA. MUITO ÚTIL PARA APRESENTAR RESULTADOS COMO NESTE CASO*/
DECLARE @CONTADOR_NOTAS INT

SET @LIMITE_MINIMO = 1
SET @LIMITE_MAXIMO = 1000000
SET NOCOUNT ON /*USADO PARA NÃO MOSTRAR RESULTADOS DE SAÍDA DE DADOS NO CONSOLE*/

WHILE @LIMITE_MINIMO <= @LIMITE_MAXIMO
BEGIN
	SELECT @CONTADOR_NOTAS = COUNT(*) FROM DBO.[NOTAS FISCAIS] WHERE NUMERO = @LIMITE_MINIMO
	IF @CONTADOR_NOTAS > 0
	BEGIN
		INSERT INTO @TABELA_NUMEROS VALUES (@LIMITE_MINIMO, 'É UMA NOTA FISCAL', DBO.FATURAMENTONOTA(@LIMITE_MINIMO)) /*FAZENDO USO DE UMA FUNÇÃO EM UM LOOP*/
	END
	ELSE
	BEGIN
		INSERT INTO @TABELA_NUMEROS VALUES (@LIMITE_MINIMO, 'NÃO É UMA NOTA FISCAL', 0)
	END
	SET @LIMITE_MINIMO = @LIMITE_MINIMO + 1
END
SELECT * FROM @TABELA_NUMEROS ORDER BY NUMERO



/*	DESAFIO: FAZER UM LOOP PARA ARMAZENAR EM UMA TABELA TEMPORÁRIA TODAS OS BAIRROS DE UMA CIDADE*/

DECLARE @BAIRRO VARCHAR(100)
DECLARE @CIDADE VARCHAR (100)
DECLARE @TOTAL_BAIRROS INT
DECLARE @CONTADOR INT
DECLARE @TABELA_BAIRROS TABLE (BAIRRO VARCHAR(100))

SET @CIDADE = 'RIO DE JANEIRO'
SET @CONTADOR = 0
SELECT @TOTAL_BAIRROS = COUNT(*) FROM (	SELECT DISTINCT BAIRRO
										FROM [TABELA DE CLIENTES]
										WHERE CIDADE = @CIDADE) X
WHILE @CONTADOR <= @TOTAL_BAIRROS
BEGIN
	SELECT DISTINCT @BAIRRO = BAIRRO
	FROM [TABELA DE CLIENTES]
	WHERE CIDADE = @CIDADE
	ORDER BY BAIRRO
	OFFSET @CONTADOR ROWS /*DETERMINA A PARTIR DE QUAL LINHA IRÁ COMEÇAR A EXIBIR OS VALORES DA TABELA*/
	FETCH NEXT 1 ROWS ONLY /*DETERMINA QUANTAS LINHAS SERÃO EXIBIDAS*/
	
	INSERT INTO @TABELA_BAIRROS VALUES (@BAIRRO)

	SET @CONTADOR = @CONTADOR + 1
END

SELECT * FROM @TABELA_BAIRROS ORDER BY BAIRRO