--j¡ SABEMOS QUE … POSSÕVEL APELIDAR UM CAMPO DE UMA TABELA COM O COMANDO 'AS'. EX:
SELECT NOME, CPF AS CODIGO, ESTADO, BAIRRO FROM TABELA_DE_CLIENTES;

--MAS TAMB…M … POSSÕVEL APELIDAR UMA TABELA, COMO NA FORMA A SEGUIR, MAS N√O USAMOS 'AS' NESSE CASO. EX:
SELECT TDC.NOME, TDC.CPF, TDC.BAIRRO FROM TABELA_DE_CLIENTES TDC;

/*ESSE FORMATO … MUITO USADO PARA CASOS EM QUE TEMOS MAIS DE UMA TABELA E QUE ESSAS TABELAS POSSUAM CAMPOS COM NOMES SEMELHANTES.
DESSA FORMA … POSSÕVEL IDENTIFICAR MAIS FACILMENTE QUAL CAMPO PERTENCE A QUAL TABELA MAIS FACILMENTE.*/