--CLASSIFICA OS PRODUTOS COM BASE EM SEU VALOR. É POSSÍVEL USAR O ALIAS DO CASE NA CLÁUSULA ORDER BY
SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA, 
(CASE
	
	WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
	WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
	ELSE 'PRODUTO BARATO'

END) AS CLASSIFICACAO
FROM TABELA_DE_PRODUTOS
ORDER BY CLASSIFICACAO;

/*CLASSIFICA OS PRODUTOS COM BASE EM SEU VALOR E SOMA A QUANTIDADE DE PRODUTOS EM CADA CATEGORIA. A CLÁUSULA GROUP BY NÃO ACEITA ALIAS.*/
SELECT
	(CASE
	
		WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
		WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
		ELSE 'PRODUTO BARATO'

	END) AS CLASSIFICACAO,
	COUNT(*) AS NUMERO_DE_PRODUTOS

FROM TABELA_DE_PRODUTOS
GROUP BY
	(CASE
	
		WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
		WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
		ELSE 'PRODUTO BARATO'

	END);


SELECT 

	TDC.NOME AS NOME_CLIENTE,
	(CASE
		WHEN TDC.LIMITE_DE_CREDITO >= 150000 THEN 'CLIENTE GRANDE'
		WHEN TDC.LIMITE_DE_CREDITO >= 110000 AND TDC.LIMITE_DE_CREDITO < 150000 THEN 'CLIENTE MEDIO'
		ELSE 'CLIENTE PEQUENO'
	END) AS CLASSIFICACAO

FROM TABELA_DE_CLIENTES TDC
ORDER BY CLASSIFICACAO;
