--EXPRESSÕES IGUAIS
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Manga' OR SABOR = 'Laranja'OR SABOR = 'Melancia';
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR IN ('Manga', 'Laranja', 'Melancia');

SELECT * FROM TABELA_DE_CLIENTES WHERE IDADE >= 20 AND ESTADO = 'SP';

--EXPRESSÕES IGUAIS
SELECT * FROM TABELA_DE_CLIENTES WHERE IDADE >= 20 AND IDADE <= 30;
SELECT * FROM TABELA_DE_CLIENTES WHERE IDADE BETWEEN 20 AND 30;

SELECT * FROM TABELA_DE_CLIENTES
WHERE 
	(CIDADE = 'São Paulo' OR CIDADE = 'Rio de Janeiro')
	AND
	(IDADE BETWEEN 20 AND 30);