--A CLÁSULA HAVING FUNCIONA SEMELHANTE AO WHERE, MAS É APLICADO APÓS O GROUP BY COM UM FILTRO QUE ENVOLVA UMA FUNÇÃO DE AGREGAÇÃO

--CONSULTA O LIMITE DE CREDITO TOTAL DOS ESTADOS
SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS CREDITO
FROM TABELA_DE_CLIENTES
GROUP BY ESTADO;

--CONSULTA O LIMITE DE CREDITO TOTAL DOS ESTADOS EM QUE O LIMITE DE CREDITO É MAIOR QUE 900000
SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS CREDITO
FROM TABELA_DE_CLIENTES
GROUP BY ESTADO
HAVING SUM(LIMITE_DE_CREDITO) >= 900000;
	
--AO TENTAR FAZER ISSO COM O WHERE, TEMOS UM ERRO
SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS CREDITO
FROM TABELA_DE_CLIENTES
WHERE SUM(LIMITE_DE_CREDITO) >= 900000
GROUP BY ESTADO;

--CONSULTA OS VALORES MÁXIMOS E MÍNIMOS DAS EMBALAGENS
SELECT 

	EMBALAGEM,
	MAX(PRECO_DE_LISTA) AS VALOR_MAX,
	MIN(PRECO_DE_LISTA) AS VALOR_MIN

FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM;

--CONSULTA OS VALORES MÁXIMOS E MÍNIMOS DAS EMBALAGENS, EM QUE O VALOR MÍNIMO NÃO PODE SER MENOR QUE DEZ
SELECT 

	EMBALAGEM,
	MAX(PRECO_DE_LISTA) AS VALOR_MAX,
	MIN(PRECO_DE_LISTA) AS VALOR_MIN

FROM TABELA_DE_PRODUTOS
WHERE PRECO_DE_LISTA >= 10
GROUP BY EMBALAGEM;

/*CONSULTA OS VALORES MÁXIMOS E MÍNIMOS DAS EMBALAGENS EM QUE O VALOR MÍNIMO ACEITO NÃO É MENOR QUE DEZ E QUE O VALOR MÁXIMO 
SEJA MAIOR QUE 20*/
SELECT 

	EMBALAGEM,
	MAX(PRECO_DE_LISTA) AS VALOR_MAX,
	MIN(PRECO_DE_LISTA) AS VALOR_MIN

FROM TABELA_DE_PRODUTOS
WHERE PRECO_DE_LISTA >= 10
GROUP BY EMBALAGEM
HAVING MAX(PRECO_DE_LISTA) >= 20;

--CONSULTA OS PRODUTOS CUJO TOTAL DE VENDAS SUPEROU 394000 UNIDADES, ORDENANDO DO MAIOR PARA O MENOR
SELECT 
	
	CODIGO_DO_PRODUTO	AS	PRODUTO,
	SUM(QUANTIDADE)		AS	TOTAL_VENDIDO
	
FROM ITENS_NOTAS_FISCAIS
GROUP BY CODIGO_DO_PRODUTO
	
	HAVING SUM(QUANTIDADE) >= 394000
	
ORDER BY SUM(QUANTIDADE) DESC;