--EXIBE AS PRIMEIRAS DEZ VENDAS DA DATA DETERMINADA
SELECT TOP 10 * FROM NOTAS_FISCAIS WHERE DATA_VENDA = '2017-10-01';

--EXIBE OS 5 PRODUTOS MAIS CAROS
SELECT TOP 5 * FROM TABELA_DE_PRODUTOS ORDER BY PRECO_DE_LISTA DESC;

--EXIBE A MAIOR QUANTIDADE DE VENDA DO DETERMINADO PRODUTO
	--PRIMEIRO ENCONTRAMOS O CÓDIGO DO PRODUTO
SELECT * FROM TABELA_DE_PRODUTOS WHERE NOME_DO_PRODUTO = 'LINHA REFRESCANTE - 1 LITRO - MORANGO/LIMAO';
	--DEPOIS FAZEMOS A CONSULTA
SELECT * FROM ITENS_NOTAS_FISCAIS WHERE CODIGO_DO_PRODUTO = 1101035 ORDER BY QUANTIDADE DESC;