-- QUERY FEITA USANDO HAVING
SELECT 

	INF.CODIGO_DO_PRODUTO, 
	TP.NOME_DO_PRODUTO, 
	SUM(INF.QUANTIDADE) AS QUANTIDADE

FROM ITENS_NOTAS_FISCAIS  INF

INNER JOIN TABELA_DE_PRODUTOS TP 
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO

GROUP BY 

	INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO HAVING SUM(INF.QUANTIDADE) > 394000 

ORDER BY SUM(INF.QUANTIDADE) DESC;

-- QUERY FEITA USANDO SUBQUERY
SELECT

	QTD_PRODUTO.CODIGO_DO_PRODUTO		AS		CODIGO_PRODUTO,
	QTD_PRODUTO.NOME_DO_PRODUTO			AS		NOME_PRODUTO,
	QTD_PRODUTO.QUANTIDADE				AS		QUANTIDADE

FROM

	(SELECT 

		INF.CODIGO_DO_PRODUTO, 
		TP.NOME_DO_PRODUTO, 
		SUM(INF.QUANTIDADE) AS QUANTIDADE

	FROM ITENS_NOTAS_FISCAIS  INF

	INNER JOIN TABELA_DE_PRODUTOS TP 
	ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO

	GROUP BY 

	INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO) QTD_PRODUTO

WHERE QTD_PRODUTO.QUANTIDADE >= 394000
ORDER BY QTD_PRODUTO.QUANTIDADE DESC;