SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES;
-- 12 BAIRROS DE CLIENTES

SELECT DISTINCT BAIRRO FROM  TABELA_DE_VENDEDORES;
-- 4 BAIRROS DE VENDEDORES

/*AO USARMOS O UNION NESSAS NOSSAS DUAS CONSULTAS, TEREMOS UM TOTAL DE 13 BAIRROS. ISSO PORQUE O UNION É UMA CONSULTA COM DISTINCT,
SENDO ASSIM, NÃO SERÁ APRESENTADO OS BAIRROS QUE ESTÃO NAS DUAS TABELAS DUAS VEZES*/

SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES
UNION
SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES;

-- SE QUISERMOS VER A CONSULTA SEM O DISTINCT, PODEMOS USAR O UNION ALL E TEREMOS OS 16 RESULTADOS
SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES
UNION ALL
SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES;