/*VIEWS SÃO COMANDOS QUE PODEM SEREM FEITOS PARA CRIAR UMA CONSULTA QUE IRÁ SE "PORTAR COMO TABELA", MUITO USADA
EM CASOS EM QUE É NECESSÁRIO FAZER USO REPETIDO DE SUBQUERIES. APÓS A CRIAÇÃO, É POSSÍVEL VERIFICAR NO MENU DE
'EXIBIÇÕES'. ESSA É A CRIAÇÃO DE UMA VIEW:*/

CREATE VIEW MEDIA_EMBALAGENS AS
SELECT

	EMBALAGEM,
	AVG(PRECO_DE_LISTA)		AS		PRECO_MEDIO

FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM;

-- ASSIM, PODEREMOS USAR ESSA CONSULTA NOVAMENTE APENAS CHAMANDO 'MEDIA_EMBALAGENS'.

SELECT EMBALAGEM, PRECO_MEDIO
FROM MEDIA_EMBALAGENS
WHERE PRECO_MEDIO <= 10;