/*PROCEDIMENTO PARA FAZER A CRIAÇÃO DE UMA FUNÇÃO NO SQL*/

CREATE FUNCTION FATURAMENTONOTA (@NUMERO AS INT) /*CRIA FUNÇÃO PASSANDO OS PARÂMETROS QUE SERÃO USADOS E O SEU TIPO, NESSE CASO, O PARÂMETRO SERÁ A VARIÁVEL NUMERO DO TIPO INT*/
RETURNS FLOAT /*DEFINE O TIPO DE RETORNO QUE A FUNÇÃO TERÁ, NESSE CASO, SERÁ UM RETORNO DO TIPO FLOAT*/
AS
BEGIN

DECLARE @FATURAMENTO FLOAT

SELECT	@FATURAMENTO = SUM(QUANTIDADE * [PREÇO])

FROM [ITENS NOTAS FISCAIS] WITH (NOLOCK)

WHERE	NUMERO = @NUMERO /*O PARÂMETRO DA FUNÇÃO ESTÁ SENDO PASSADO AQUI*/

RETURN @FATURAMENTO /*E O QUE SERÁ RETORNADO PELA FUNÇÃO SE ENCONTRA AQUI*/

END

/*O COMANDO ACIMA, QUANDO EXECUTADO, IRÁ CRIAR UMA FUNCITON QUE FICARÁ DISPONÍVEL PARA SER VISUALIZADA NO BANCO DE DADOS ONDE FOI CRIADA, NO MENU:
BANCO DE DADOS -> PROGRAMAÇÃO -> FUNÇÕES*/

/*CRIANDO AGORA UMA OUTRA FUNÇÃO PARA GERAÇÃO DE NÚMEROS ALEATÓRIOS, PORÉM, PARA QUE SEJA POSSÍVEL CRIAR A FUNÇÃO, SERÁ NECESSÁRIO FAZER UMA 'GAMBIARRA' PARA QUE O SISTEMA PERMITA. ASSIM, CRIAREMOS UMA VIEW
QUE GERA UM VALOR ALEATÓRIO E ESSE VALOR ALEATÓRIO DA VIEW SERÁ ATRIBUIÍDO DEPOIS NA FUNÇÃO.*/

CREATE VIEW VW_VALORALEATORIO AS SELECT RAND() AS VALOR_ALEATORIO;

CREATE FUNCTION NUMEROALEATORIO(@VAL_MIN INT, @VAL_MAX INT)
RETURNS INT
AS
BEGIN

DECLARE @ALEATORIO INT
DECLARE @VALOR_ALEATORIO FLOAT /*ESSA VARIÁVEL É A QUE VAI RECEBER O NÚMERO ALEATÓRIO DA VIEW, JÁ QUE NÃO DARIA CERTO SE TENTASSEMOS PASSAR O VALOR RAND PARA CÁ DIRETAMENTE*/
SELECT	@VALOR_ALEATORIO = VALOR_ALEATORIO FROM VW_VALORALEATORIO /*AQUI O VALOR ESTÁ SENDO ATRIBÚIDO*/
SET @ALEATORIO = ROUND(((@VAL_MAX - @VAL_MIN - 1) * @VALOR_ALEATORIO + @VAL_MIN), 0) /*E AQUI ESTÁ O CÁLCULO QUE VAI GERAR O VALOR ALEATÓRIO*/
RETURN @ALEATORIO

END


/*AGORA, CRIANDO UMA FUNCTION QUE RETORNA O FATURAMENTO TOTAL DE TODAS AS NOTAS FISCAIS DE UM BAIRRO*/

CREATE FUNCTION FATURAMENTOBAIRRO(@BAIRRO VARCHAR(50))
RETURNS FLOAT
AS
BEGIN

DECLARE @FATURAMENTO FLOAT

SELECT	@FATURAMENTO = SUM(INF.QUANTIDADE * INF.[PREÇO])

FROM [ITENS NOTAS FISCAIS] INF WITH (NOLOCK)
INNER JOIN [NOTAS FISCAIS] NF WITH (NOLOCK)
	ON	NF.NUMERO	= INF.NUMERO
INNER JOIN [TABELA DE CLIENTES] TC WITH (NOLOCK)
	ON	TC.CPF	= NF.CPF

WHERE	TC.BAIRRO LIKE @BAIRRO

RETURN @FATURAMENTO

END

/*PARA EXECUTAR UMA FUNCTION, FAZEMOS O SEGUINTE:*/

SELECT DBO.NUMEROALEATORIO(1, 10)

SELECT DBO.FATURAMENTOBAIRRO('ÁGUA SANTA')