--AUTO INCREMENTO

/*AUTO INCREMENTO É QUANDO UM CAMPO IMPREQUEMENTA SEU VALOR SEMPRE QUE UMA NOVA LINHA É ADICIONADA NA TABALA. O VALOR DO AUTO INCREMENTO NÃO PODE SER
REMOVIDO DA TABELA, OU SEJA, MESMO QUE VOCÊ ELIMINE O ID DE AUTO INCREMENTO DE NÚMERO 1, AO GERAR UMA NOVA LINHA, O VALOR AINDA ASSIM SERÁ DOIS. E
POR FIM, NÃO É POSSÍVEL ADICIONAR UM VALOR NOVO NO AUTO INCREMENTO AO SE FAZER UM INSERTO.
É FEITO DA SEGUINTE FORMA:*/

--CREATE TABLE TAB_INCREMENTO (
--	ID INT IDENTITY(1,1) NOT NULL, --ESSA SERIA A FORMA DE FAZER A CRIAÇÃO DE UM CAMPO COM AUTO INCREMENTO, DEFININDO O NOME, TIPO, E PRECISA SER NOT NULL
--	DESCRITOR VARCHAR(20) NULL
--);

/*VEJA QUE A FUNÇÃO IDENTITY POSSUIM DOIS PARÂMETROS, SENDO O PRIMEIRO RESPONSÁVEL POR DEFINIR EM QUAL VALOR IRÁ COMEÇAR A CONTAGEM, E O SEGUNDO DEFINE
QUANTO SERÁ INCREMENTADO POR CONTAGEM.*/


--DEFAULT
/*DEFAULT É A DEFINIÇÃO DE UM VALOR PADRÃO PARA UM CAMPO, QUANDO SEU VALOR NÃO FOR ESPECIFICADO NA HORA DE INSERIR VALORES NA TABELA. PEGANDO COMO EXEMPLO
O MESMO CÓDIGO ACIMA, TEMOS O SEGUINTE:*/

--CREATE TABLE TAB_INCREMENTO
--ID INT IDENTITY(1, 1) NOT NULL --PRECISA SER NOT NULL PORQUE SERÁ SEMPRE INCREMENTADO
--DESCRITOR VARCHAR(20) NULL --O DEFAULT DESSE CAMPO É NULL, OU SEJA, QUANDO FOREM INSERIDOS VALORES, MAS NÃO FOREM ESPECIFICADOS, SERÁ CONSIDERADO NULL
--CIDADE VARCHAR(100) DEFAULT 'Rio de Janeiro' --COM ESSE PADRÃO, QUANDO NÃO HOUVER ESPECIFICAÇÃO DA CIDADE, O VALOR SERÁ CONSIDERADO 'Rio de Janeiro'
--DATA DATE DEFAULT GETDATE() --AQUI, FOI USADA UMA FUNÇÃO PARA SEMPRE PEGAR A DATA ATUAL NA INCLUSÃO DE UMA LINHA NA TABELA