--COMANDO MAIS SIMPLES PARA CRIAÇÃO DE BANCO DE DADOS, QUE CRIA DE FORMA PADRONIZADA
CREATE DATABASE VENDAS_SUCOS;

/*COMANDO PARA CRIAÇÃO DE BANCO DE DADOS CUSTOMIZADO, ONDE INFORMAMOS OS DADOS DE NOME DOS ARQUIVOS LÓGICOS, DE DADOS E DE LOGS (COMO UM ARQUIVO DE REGISTRO 
DO QUE É FEITO NO BANCO DE DADOS, USADO PARA RECUPERAÇÃO DE PONTOS DE SALVAMENTO, POR EXEMPLO), LOCAL DE ARQUIVO, TAMANHO E  CRESCIMENTO.*/
CREATE DATABASE VENDAS_SUCOS2
ON( --CRIAÇÃO DOS ARQUIVOS LÓGICOS DE DADOS
NAME = 'VENDAS_SUCOS2_DAT', --NOME LÓGICO
FILENAME = 'C:\TESTES\VENDAS_SUCOS2.MDF', --LOCAL DE ARQUIVO ONDE SERÁ SALVO O ARQUIVO
SIZE = 10, --TAMANHO DO ARQUIVO EM MB
MAXSIZE = 50, --TAMANHO MÁXIMO DO BANCO EM MB
FILEGROWTH = 5 --TAMANHO DE CRESCIMENTO DO BANCO, NESTE CASO, DE 5MB EM 5MB
)
LOG ON( --CRIAÇÃO DOS ARQUIVOS LÓGICOS DE LOGS
NAME = 'VENDAS_SUCOS2_LOG',
FILENAME = 'C:\TESTES\VENDAS_SUCOS2.LDF',
SIZE = 10,
MAXSIZE = 50,
FILEGROWTH = 5
);

--FAZER A EXCLUSÃO DE UM BANCO DE DADOS, BASTA USAR O COMANDO A SEGUIR
DROP DATABASE VENDAS_SUCOS2