--PADRÃO PARA CRIAÇÃO DOS CAMPOS DAS TABELAS É: PRIMEIRO INFORMA O NOME DO CAMPO, DEPOIS O TIPO, E POR FIM SE ACEITA NULO OU NÃO
CREATE TABLE PRODUTOS(
	CODIGO VARCHAR(10) NOT NULL,
	DESCRITOR VARCHAR(100) NULL,
	SABOR VARCHAR(50) NULL,
	TAMANHO VARCHAR(50) NULL,
	EMBALAGEM VARCHAR(50) NULL,
	PRECO_LISTA FLOAT NULL,
	PRIMARY KEY (CODIGO) --DEFINIÇÃO DE QUAL CAMPO SERÁ CHAVE PRIMÁRIA
);

CREATE TABLE VENDEDORES(
	MATRICULA VARCHAR(5) NOT NULL,
	NOME VARCHAR(100) NULL,
	BAIRRO VARCHAR(50) NULL,
	COMISSAO FLOAT NULL,
	DATA_ADMISSAO DATE NULL,
	FERIAS BIT NULL,
	PRIMARY KEY (MATRICULA)
);

CREATE TABLE CLIENTES(
	CPF VARCHAR(11) NOT NULL,
	NOME VARCHAR(100) NULL,
	ENDERECO VARCHAR(150) NULL,
	BAIRRO VARCHAR(50) NULL,
	CIDADE VARCHAR(50) NULL,
	ESTADO VARCHAR(50) NULL,
	CEP VARCHAR(8) NULL,
	DATA_NASCIMENTO DATE NULL,
	IDADE INTEGER NULL,
	GENERO VARCHAR(1) NULL,
	LIMITE_CREDITO FLOAT NULL,
	VOLUME_COMPRA FLOAT NULL,
	PRIMEIRA_COMPRA BIT NULL,
	PRIMARY KEY (CPF)
);

CREATE TABLE TABELA_DE_VENDAS(
	NUMERO VARCHAR(5) NOT NULL,
	DATA DATE NULL,
	CPF VARCHAR(11) NOT NULL, --CHAVE ESTRANGEIRA COM A TABELA DE CLINTES, PORTANTO NÃO PODE SER NULO
	MATRICULA VARCHAR(5) NOT NULL, --CHAVE ESTRANGEIRA COM A TABELA DE VENDEDORES, PORTANTO NÃO PODE SER NULO
	IMPOSTO FLOAT NULL,
	PRIMARY KEY (NUMERO)
);

/*PARA CRIARMOS A CHAVE ESTRANGEIRA, CRIAMOS A PARTIR DA TABELA QUE POSSUI CARDINALIDADE N. NESSE CASO, PEGANDO A TABELA_DE_VENDAS E DE CLIENTES COMO EXEMPLO,
UM CLIENTE PODE COMPRAR VÁRIAS VEZES NA MESMA LOJA, TEM VÁRIAS NOTAS FISCAIS, MAS CADA NOTA POSSUI APENAS UM CLIENTE. SENDO ASSIM, COMO A TABELA_DE_VENDAS É 
QUE POSSUI O VALOR DE CARDINALIDADE N, É NELA QUE SERÁ CRIADA A CHAVE ESTRANGEIRA*/

ALTER TABLE TABELA_DE_VENDAS --DÁ O COMANDO DE QUE A TABELA SERÁ ALTERADA, NESSE CASO, PARA ADICIONAR A CHAVE ESTRANGEIRA
ADD CONSTRAINT FK_CLIENTES /*ADICIONA A RESTRIÇÃO, QUE É UMA REGRA QUE O BANCO DE DADOS DEVE RESPEITAR, EM QUE SÓ POSSO TER CPFs NA TABELA DE VENDAS QUE JÁ ESTEJAM
CADASTRADOS NA TABELA DE CLIENTES. NORMALMENTE, O NOME DADO À RESTRIÇÃO, DO TIPO DE CHAVE ESTRANGEIRA, SEGUEM O PADRÃO DE FK_NOME_DO_CAMPO.*/
FOREIGN KEY (CPF) REFERENCES CLIENTES (CPF)/*É ESPECIFICADO O TIPO DE RESTRIÇÃO, FOREING KEY, EM QUE O CAMPO CPF DA TABELA_DE_VENDAS DEVE SER IGUAL AO CAMPO
CPF DA TABELA DE CLIENTES.*/

ALTER TABLE TABELA_DE_VENDAS
ADD CONSTRAINT FK_VENDEDORES
FOREIGN KEY (MATRICULA) REFERENCES VENDEDORES (MATRICULA)

/*CASO HOUVER ALGUMA DIFERENÇA ENTRE OS CAMPOS E SUAS PROPRIEDADES QUE ESTÃO SENDO PASSADOS COMO REFERÊNCIAS PARA CRIAÇÃO DAS CHAVES ESTRANGEIRAS, ESSE COMANDO
NÃO SERIA POSSÍVEL. SENDO ASSIM, RESTARIAM DUAS OPÇÕES: USAR UM DROP TABLE NAS TABELAS DE CLIENTES E VENDAS, POIS É PRECISA ALTERAR A PRIMEIRA E A SEGUNDA DEPENDE
DELA, OU USAR O COMANDO A SEGUIR:

	ALTER TABLE TABELA_QUE_SERÁ_ALTERADA
	ALTER COLUMN COLUNA_QUE_SERÁ_ALTERADA NOVAS_PROPRIEDADES

POR EXEMPLO, CASO O CAMPO MATRICULA DA TABELA DE VENDEDORES, COM VARCHAR(5), FOSSE DECLARADO COM VARCHAR(11) NA TABELA_DE_VENDAS, FICARIA ASSIM:

	ALTER TABLE TABELA_DE_VENDAS
	ALTER COLUMN MATRICULA VARCHAR(5) NOT NULL

ESSA FUNÇÃO, PORÉM, SÓ É VÁLIDA SE NÃO FUNCIONA SE HOUVER UMA CHAVE ESTRANGEIRA NO CAMPO QUE SERÁ ALTERADO.
*/

CREATE TABLE TABELA_ITENS_VENDIDOS(
	NUMERO VARCHAR(5) NOT NULL,
	CODIGO VARCHAR(10) NOT NULL,
	QUANTIDADE INTEGER NULL,
	PRECO FLOAT NULL,
	PRIMARY KEY (NUMERO, CODIGO)--MAIS DE UM CAMPO PODEM SER CHAVES PRIMÁRIAS
);

ALTER TABLE TABELA_ITENS_VENDIDOS
ADD CONSTRAINT FK_NUMERO
FOREIGN KEY (NUMERO) REFERENCES TABELA_DE_VENDAS (NUMERO);

ALTER TABLE TABELA_ITENS_VENDIDOS
ADD CONSTRAINT FK_CODIGO
FOREIGN KEY (CODIGO) REFERENCES PRODUTOS (CODIGO);