/*RELATÓRIO QUE VERIFICA SE, EM DETERMINADO MÊS, OS CLIENTES ULTRAPASSARAM OU NÃO O VOLUME DE COMPRAS PERMITIDO
NO CONTRATO
TABELAS DE CLIENTE, NOTAS FISCAIS, ITENS DE NOTAS FISCAIS
*/

--VERIFICA O TOTAL VENDIDO POR CLIENTE
SELECT

	NF.CPF											AS		CPF_CLIENTE,
	CONVERT(VARCHAR(7), NF.DATA_VENDA, 120)			AS		MES_ANO,
	SUM(INF.QUANTIDADE)								AS		QUANTIDADE_TOTAL

FROM NOTAS_FISCAIS									NF
INNER JOIN ITENS_NOTAS_FISCAIS						INF
ON NF.NUMERO = INF.NUMERO

GROUP BY

	NF.CPF,
	CONVERT(VARCHAR(7), NF.DATA_VENDA, 120)

--USA A QUERY ANTERIOR COMO UMA NOVA TABELA PARA FAZER UM JOIN E VERIFICAR A SITUAÇÃO DO CLIENTE
SELECT

	TC.CPF,
	TC.NOME,
	TC.VOLUME_DE_COMPRA,
	TV.QUANTIDADE_TOTAL,
	TV.MES_ANO,
	(CASE WHEN

		TV.QUANTIDADE_TOTAL >= TC.VOLUME_DE_COMPRA THEN 'VENDAS_INVALIDAS'
		ELSE 'VENDAS_VALIDAS' END
	
	)	AS	SITUACAO

FROM TABELA_DE_CLIENTES TC
INNER JOIN
(
SELECT

	NF.CPF											AS		CPF_CLIENTE,
	CONVERT(VARCHAR(7), NF.DATA_VENDA, 120)			AS		MES_ANO,
	SUM(INF.QUANTIDADE)								AS		QUANTIDADE_TOTAL

FROM NOTAS_FISCAIS									NF
INNER JOIN ITENS_NOTAS_FISCAIS						INF
ON NF.NUMERO = INF.NUMERO

GROUP BY

	NF.CPF,
	CONVERT(VARCHAR(7), NF.DATA_VENDA, 120)
) TV
ON TV.CPF_CLIENTE = TC.CPF


/*AGORA É NECESSÁRIO UMA COMPLEMENTAÇÃO DO RELATÓRIO, INFORMANDO SOMENTE OS CLIENTES QUE TÊM A SITUAÇÃO
INVÁLIDA E APRESENTANDO A DIFERENÇA ENTRE O VOLUME DE COMPRA E A QUANTIDADE TOTAL COMPRADA PELO CLIENTE EM
PERCENTUAL*/

SELECT

	TC.CPF,
	TC.NOME,
	TC.VOLUME_DE_COMPRA,
	TV.QUANTIDADE_TOTAL,
	ROUND((1 - (TC.VOLUME_DE_COMPRA / TV.QUANTIDADE_TOTAL) * 100), 2)	AS	PORCENTAGEM,
	TV.MES_ANO,
	(CASE WHEN

		TV.QUANTIDADE_TOTAL >= TC.VOLUME_DE_COMPRA THEN 'VENDAS_INVALIDAS'
		ELSE 'VENDAS_VALIDAS' END
	
	)	AS	SITUACAO

FROM TABELA_DE_CLIENTES TC
INNER JOIN
(
SELECT

	NF.CPF											AS		CPF_CLIENTE,
	CONVERT(VARCHAR(7), NF.DATA_VENDA, 120)			AS		MES_ANO,
	SUM(INF.QUANTIDADE)								AS		QUANTIDADE_TOTAL

FROM NOTAS_FISCAIS									NF
INNER JOIN ITENS_NOTAS_FISCAIS						INF
ON NF.NUMERO = INF.NUMERO

GROUP BY

	NF.CPF,
	CONVERT(VARCHAR(7), NF.DATA_VENDA, 120)
) TV
ON TV.CPF_CLIENTE = TC.CPF

WHERE

	(TC.VOLUME_DE_COMPRA - TV.QUANTIDADE_TOTAL) < 0;

--RESOLUÇÃO PROFESSOR
SELECT
TC.CPF, TC.NOME, TC.VOLUME_DE_COMPRA, TV.MES_ANO, TV.QUANTIDADE_TOTAL,
(CASE WHEN TC.VOLUME_DE_COMPRA >= TV.QUANTIDADE_TOTAL THEN 'VENDAS VÁLIDAS'
ELSE 'VENDAS INVÁLIDAS' END) AS RESULTADO,
ROUND((1 - (TC.VOLUME_DE_COMPRA/TV.QUANTIDADE_TOTAL)) * 100, 2) AS PERCENTUAL
FROM TABELA_DE_CLIENTES TC
INNER JOIN
(
SELECT 
NF.CPF
,CONVERT(VARCHAR(7), NF.DATA_VENDA, 120) AS MES_ANO
,SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
GROUP BY
NF.CPF
, CONVERT(VARCHAR(7), NF.DATA_VENDA, 120)
) TV
ON TV.CPF = TC.CPF
WHERE 
(TC.VOLUME_DE_COMPRA - TV.QUANTIDADE_TOTAL) < 0;
