 /*RELATÓRIO INFORMANDO AS VENDAS ANUAIS DOS PRODUTOS POR SABOR, ORDENANANDO DO QUE MAIS VENDEU PARA O QUE
 MAIS VENDEU. ALÉM DISSO, UMA APRESENTAÇÃO DE QUAL A PORCENTAGEM DO TOTAL DE PRODUTOS VENDIDOS AQUELE SABOR
 REPRESENTA*/

--ENCONTRA O TOTAL DE VENDAS DE UM PRODUTO POR ANO
SELECT

	TP.SABOR				AS		SABOR,
	YEAR(NF.DATA_VENDA)		AS		ANO,
	SUM(INF.QUANTIDADE)		AS		QUANTIDADE


FROM ITENS_NOTAS_FISCAIS (NOLOCK) INF
INNER JOIN NOTAS_FISCAIS (NOLOCK) NF
ON INF.NUMERO = NF.NUMERO
INNER JOIN TABELA_DE_PRODUTOS (NOLOCK) TP
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO

GROUP BY
	TP.SABOR,
	YEAR(NF.DATA_VENDA)
ORDER BY
	YEAR(NF.DATA_VENDA),
	SUM(INF.QUANTIDADE) DESC;

--ENCONTRA O TOTAL DE VENDAS DE TODOS OS PRODUTOS POR ANO
SELECT

	SUM(INF.QUANTIDADE)		AS		TOTAL_VENDAS,
	YEAR(NF.DATA_VENDA)		AS		ANO

FROM ITENS_NOTAS_FISCAIS (NOLOCK) INF
INNER JOIN  NOTAS_FISCAIS (NOLOCK) NF
ON NF.NUMERO = INF.NUMERO

GROUP BY
	YEAR(NF.DATA_VENDA);


--FAZ A JUNÇÃO DAS DUAS TABELAS PARA PERMITIR A CRIAÇÃO DO RELATÓRIO
SELECT

	V_ANO.ANO											AS		ANO,
	V_ANO.TOTAL_VENDAS									AS		TOTAL_VENDAS,
	V_PROD.SABOR										AS		SABOR,
	V_PROD.QUANTIDADE									AS		QUANT_PRODUTO,
	ROUND(CONVERT(FLOAT, V_PROD.QUANTIDADE) / CONVERT(FLOAT, V_ANO.TOTAL_VENDAS) * 100, 2 )		
														AS		PORCENTAGEM_VENDAS

FROM
	(
	SELECT

		TP.SABOR				AS		SABOR,
		YEAR(NF.DATA_VENDA)		AS		ANO,
		SUM(INF.QUANTIDADE)		AS		QUANTIDADE


	FROM ITENS_NOTAS_FISCAIS (NOLOCK) INF
	INNER JOIN NOTAS_FISCAIS (NOLOCK) NF
	ON INF.NUMERO = NF.NUMERO
	INNER JOIN TABELA_DE_PRODUTOS (NOLOCK) TP
	ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO

	GROUP BY
		TP.SABOR,
		YEAR(NF.DATA_VENDA)
	) V_PROD
INNER JOIN
(
	SELECT

		SUM(INF.QUANTIDADE)		AS		TOTAL_VENDAS,
		YEAR(NF.DATA_VENDA)		AS		ANO

	FROM ITENS_NOTAS_FISCAIS (NOLOCK) INF
	INNER JOIN  NOTAS_FISCAIS (NOLOCK) NF
	ON NF.NUMERO = INF.NUMERO

	GROUP BY
		YEAR(NF.DATA_VENDA)
	) V_ANO
ON V_ANO.ANO = V_PROD.ANO
ORDER BY
	V_ANO.ANO,
	V_PROD.QUANTIDADE DESC;

/*CASO QUISERMOS FAZER O MESMO TIPO DE RELATÓRIO, MAS POR TAMANHO AO INVÉS DE SABOR, PODEMOS FAZER DA SEGUINTE
MANEIRA*/
SELECT

	V_ANO.ANO											AS		ANO,
	V_ANO.TOTAL_VENDAS									AS		TOTAL_VENDAS,
	V_PROD.TAMANHO										AS		TAMANHO,
	V_PROD.QUANTIDADE									AS		QUANT_PRODUTO,
	ROUND(CONVERT(FLOAT, V_PROD.QUANTIDADE) / CONVERT(FLOAT, V_ANO.TOTAL_VENDAS) * 100, 2 )		
														AS		PORCENTAGEM_VENDAS

FROM
	(
	SELECT

		TP.TAMANHO				AS		TAMANHO,
		YEAR(NF.DATA_VENDA)		AS		ANO,
		SUM(INF.QUANTIDADE)		AS		QUANTIDADE


	FROM ITENS_NOTAS_FISCAIS (NOLOCK) INF
	INNER JOIN NOTAS_FISCAIS (NOLOCK) NF
	ON INF.NUMERO = NF.NUMERO
	INNER JOIN TABELA_DE_PRODUTOS (NOLOCK) TP
	ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO

	GROUP BY
		TP.TAMANHO,
		YEAR(NF.DATA_VENDA)
	) V_PROD
INNER JOIN
(
	SELECT

		SUM(INF.QUANTIDADE)		AS		TOTAL_VENDAS,
		YEAR(NF.DATA_VENDA)		AS		ANO

	FROM ITENS_NOTAS_FISCAIS (NOLOCK) INF
	INNER JOIN  NOTAS_FISCAIS (NOLOCK) NF
	ON NF.NUMERO = INF.NUMERO

	GROUP BY
		YEAR(NF.DATA_VENDA)
	) V_ANO
ON V_ANO.ANO = V_PROD.ANO
ORDER BY
	V_ANO.ANO,
	V_PROD.QUANTIDADE DESC;