/*AS TRANSAÇÕES SÃO MEDIDAS DE SEGURANÇA QUE FUNCIONAM COMO 'BACKUPS'. CASO FOR NECESSÁRIO FAZER UMA SÉRIE DE COMANDOS SENSÍVEIS EM UM BANCO DE DADOS
MUITO IMPORTANTE, É INTERESSANTE FAZER SEU USO JUSTAMENTE PARA EVITAR ERROS.
FUNCIONA EM 3 COMANDOS:
BEGIN TRANSACTION	->	CRIA UM PONTO DE 'BACKUP' NO ARQUIVO EM QUE, A PARTIR DESSA COMANDO, NENHUM OUTRO COMANDO COMO DELETE, INSERT OU UPDATE SEJA
						IMPOSSÍVEL DE SE RETORNAR
COMMIT				->	APÓS AS ALTERAÇÕES SEREM FEITOS E FOR VERIFICADO QUE NENHUM ERRO OCORREU E ESTÁ TUDO FUNCIONANDO COMO DEVERIA, É EXECUTADO O
						COMANDO PARA 'OFICIALIZAR' O QUE FOI FEITO.
ROLLBACK			->	ESSE COMANDO É USADO PARA O CASO DE QUE ALGUMA ALTERAÇÃO QUE TENHA SIDO FEITA DE FORMA INDEVIDA SEJA DESFEITA

UM PONTO IMPORTANTE DE SE FALAR É QUE, APÓS INICIAR UMA TRANSAÇÃO COM BEGIN TRANSACTION, AS TABELAS QUE SOFREREM MUDANÇAS FICAM TEMPORARIAMENTE 
INDISPONÍVEIS ATÉ QUE SEJA EXECUTADO OU O COMMIT OU O ROLLBACK, ENTÃO TAMBÉM É NECESSÁRIO TER CUIDADO COM ISSO PARA EVITAR PARADAS IMPREVISTAS PARA
OUTROS USUÁRIOS.
*/

BEGIN TRANSACTION

SELECT * FROM VENDEDORES --EXECUTANDO ESSE COMANDO, VEMOS QUE TEM-SE UM TOTAL DE 4 VENDEDORES

INSERT INTO VENDEDORES VALUES(
'239', 'Iury Gontijo Silva', 'Copacabana', 1.15, '20240105', '1'
)

/*APÓS SER FEITO O INSERT DE MAIS UM, PASSAMOS A TER 5 VENDEDORES, MAS ESSE VALOR AINDA NÃO ESTÁ OFICIALMENTE GRAVADO NA TABELA. SE FOR VERIFICADO QUE
O VALOR ESTÁ CORRETO, PODERÁ SER FEITO O COMMIT PARA GRAVAR OS DADOS, OU ENTÃO O ROLLBACK, PARA DESFAZER ESSAS MUDANÇAS*/

COMMIT